### ISSUE TITLE
Communicate the existence of flathub

### ISSUE THREAD

**Issue by nedrichards** [endlessm/electron-flatpak-base-app#5]
Now the Electron base app is available on [Flathub](https://github.com/flathub/io.atom.electron.BaseApp), that strikes me as a better place for it than a random s3 bucket. We should consider deprecating our existing hosting and encouraging people to move to Flathub. (e.g. changing URLs in upstream apps like VS Code).

If we choose not to do that then we should at least mirror the improvements we made in the flathub manifest (FDo 1.6 etc.)

@cosimoc @ramcq (for flathub)
@ebassi @ptomato (for SDK team)

**Comment by ptomato** [comment]
Fixed in https://github.com/endlessm/electron-flatpak-base-app/commit/29b73189036404538391df9d1e8e65c8f3008ed9
