### ISSUE TITLE
Electron >= 2.0 requires GTK3

### ISSUE THREAD

**Issue by malept** [endlessm/electron-flatpak-base-app#7]
As of [Electron 2.0.0-beta.1](https://github.com/electron/electron/releases/tag/v2.0.0-beta.1), Electron depends on GTK3 instead of GTK2. As a result, `io.atom.electron.BaseApp.json` will need to be updated.

Will we be able to support creating flatpaks for both Electron 1.x and Electron 2.x?

**Comment by nedrichards** [comment]
The underlying Freedesktop.org SDK already contains GTK3 - so that won't be an issue. We'll continue to maintain GTK2 support in the base app whilst people are deploying electron versions that need it.
